apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-l2-policy
  namespace: kube-system
spec:
  interfaces:
    - enp5s0
    - eth.*
    - enp*.*
    - ens.*
    - wlan.*
    - wlp.*
  loadBalancerIPs: true
  externalIPs: true
