apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: main-l2-policy
  namespace: kube-system
spec:
  interfaces:
    - enp5s0
    - enp2s0
    - enp1s0
  loadBalancerIPs: true
  externalIPs: true
